### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Frolikow** [p-tka4enko/range-slider#10]
На блоках не должно быть маргинов и паддингов. Если нужно спозиционировать блок, то его нужно либо положить в элемент-обертку и позиционировать обертку, либо подумать можно ли данный блок сделать элементом ближайшего родительского блока.
В данном случае речь идет о всех блоках
![image](https://user-images.githubusercontent.com/25764783/57057272-b7418580-6cd1-11e9-8dae-d8d1caf38b17.png)
![image](https://user-images.githubusercontent.com/25764783/57057284-c3c5de00-6cd1-11e9-8127-a73fbfd8e4c7.png)
![image](https://user-images.githubusercontent.com/25764783/57057295-d3452700-6cd1-11e9-8258-51f4f261667b.png)
При чем, в случае последнего примера, у тебя на элементе два класса(блок и элемент), но при этом у тебя для класса элемента - нету ни одного стиля. Я предлагаю здесь 
![image](https://user-images.githubusercontent.com/25764783/57057875-3f298e80-6cd6-11e9-85c9-dc2acd4c800b.png)
блок перенести внутрь элемента, при этом стили для позиционирования переписать именно для элемента

**Comment by Frolikow** [comment]
Уточню, пока не сделал, паддингов не должно быть если они как-то задают внешнюю геометрию блока)

**Comment by pasha-zolotukhin** [comment]
У меня есть вопрос насчет обнуления margin, padding. Он вот здесь: https://github.com/pasha-zolotukhin/cv-project/issues/16

**Comment by pasha-zolotukhin** [comment]
У меня есть вопрос насчет обнуления margin, padding. Он вот здесь: https://github.com/pasha-zolotukhin/cv-project/issues/16#issuecomment-486624845

**Comment by Frolikow** [comment]
[Ответил](https://github.com/p-tka4enko/cv-project/issues/16#issuecomment-492494719)

**Comment by p-tka4enko** [comment]
> Уточню на счет паддинга, пока не сделал) паддинг на блоке следует задавать только в случае, если эти отступы нужны всегда. и при условии что при возможном расширении проекта, этот паддинг ни при каких обстоятельствах не будет мешать.
Так вот, в твоем случае (блок .slider-block) нужен ли паддинг на блоке? не помешает ли он в будущем? есть ли смысл перенести паддинг на элемент(-ы)?

Да, он там нужен всегда.


> При чем, в случае последнего примера, у тебя на элементе два класса(блок и элемент), но при этом у тебя для класса элемента - нету ни одного стиля. Я предлагаю здесь блок перенести внутрь элемента, при этом стили для позиционирования переписать именно для элемента

Проблема в том, что мне нужно в плагин передавать DOM элемент. Его как раз я ищу через slider-block__slider. Блока range-slider изначально там нет, его добавляет сам плагин.

**Comment by Frolikow** [comment]
> Да, он там нужен всегда.

Можешь плиз аргументировать? Просто мне кажется, что лучше в элемент обертку положить,  и ей задавать нужные отступы. 

> Проблема в том, что мне нужно в плагин передавать DOM элемент. Его как раз я ищу через slider-block__slider. Блока range-slider изначально там нет, его добавляет сам плагин.

Это понятно, но почему нельзя искать через родительский элемент, тот, который `slider-block__slider-wrapper`, а `range-slider` вставлять внутрь этого элемента, а не объединять их? И микс не будет на `div`'ке, и марджины с блока можно будет убрать. Разве не лучше получиться?)

**Comment by p-tka4enko** [comment]
> Можешь плиз аргументировать? Просто мне кажется, что лучше в элемент обертку положить, и ей задавать нужные отступы.

Не понял, если честно.

> Это понятно, но почему нельзя искать через родительский элемент, тот, который slider-block__slider-wrapper, а range-slider вставлять внутрь этого элемента, а не объединять их? И микс не будет на div'ке, и марджины с блока можно будет убрать. Разве не лучше получиться?)

А что значит "range-slider вставлять внутрь этого элемента"? Если его просто вставить в разметку, то в файле slider-block.pug будет два блока. а это вроде как не правильно.

**Comment by Frolikow** [comment]
> Не понял, если честно. Там я нарочно добавил отступ от рамки, просто чтобы элементы не прилипали к ней.

Здесь речь, например, о переиспользовании плагина, в частности блока `slider-block js-slider-block`.
Следует рассматривать, что если плагин будет использован в других условиях. Опять же как пример эквалайзер, фиксированные отступы блока будут не к месту. Другое дело если этот блок будет лежать внутри родительского элемента, и на этом элементе можно задавать позиционирование как душе угодно) 

> А что значит "range-slider вставлять внутрь этого элемента"? Если его просто вставить в разметку, то в файле slider-block.pug будет два блока, а это вроде как не правильно.

у тебя сейчас выглядит так:
```pug
mixin slider-block()
  .slider-block.js-slider-block
    .slider-block__slider-wrapper
      .slider-block__slider.js-slider-block__slider
    .slider-block__options
        //элементы панели конфига
```
что предлагаю я:
```pug
mixin slider-block()
  .slider-block.js-slider-block
    .slider-block__slider-wrapper.js-slider-block__slider-wrapper
      
    .slider-block__options
        //элементы панели конфига
```
и в таком случае ты в `js` ищешь `js-slider-block__slider-wrapper` , и внутрь него помещаешь блок плагина, опять же силами `js`. Как итог:
> И микс не будет на div'ке, и марджины с блока можно будет убрать

**Comment by p-tka4enko** [comment]
Так?
