### ISSUE TITLE
Дублирование кода

### ISSUE THREAD

**Issue by Frolikow** [p-tka4enko/range-slider#13]
В index.js сейчас у тебя три почти одинаковых фрагмента кода, которые различаются только именованием. Если например из твоих слайдеров понадобиться сделать эквалайзер, допустим полос на 15-20? index.js тогда вырастет до 1.5к-2к строк кода, что достаточно плохо. 
Задача здесь в том, чтоб твой плагин находил все блоки в которых должен быть слайдер, и в каждом блоке уже отрисовывал свой слайдер. Тут нужно будет не забыть о том, что каждый слайдер должен быть независим, т.е. при пользовании одного слайдера - остальные сохраняли свое состояние.  

P.S. Именования, в данном случае, это тоже касается. 
Пример:
```javascript
    $min1.val(min);
    $max1.val(max);
.....
    $min2.val(min);
    $max2.val(max);
.....
    $min3.val(min);
    $max3.val(max);
```
где-то дальше(если расширять приложение):
```javascript
    $min12.val(min);
    $max12.val(max);
.....
    $min16.val(min);
    $max16.val(max);
.....
    $min20.val(min);
    $max20.val(max);
```

**Comment by p-tka4enko** [comment]
Создал класс SliderBlock.
