### ISSUE TITLE
Архитектура

### ISSUE THREAD

**Issue by Frolikow** [p-tka4enko/range-slider#16]
Нужно структурировать папки. Каждый класс в отдельной папке. И папка, и файл - должны иметь одно имя, класса который они содержат.
Что касается views, папку лучше будет переименовать в View, т.к. это в первую очередь это 1 единственная View, а её разделение на части  должно касаться только View.

**Comment by Frolikow** [comment]
А можешь объяснить зачем во вьюхах ты вызываешь `this._model.getConfig();`? Почему именно так решил получать данные из модели?

**Comment by Frolikow** [comment]
Еще не совсем понятна реализация вьюх. У тебя есть MainView:
> MainView(model: Model, root: DOM Element) - полоска слайдера и сам слайдер. Основной класс. 

Почему тогда, если это главная(исходя из названия) вьюха, она у тебя по факту сама по себе? Она ведь отвечает лишь за ориентацию слайдера. Тогда лучше ее назвать SliderView(по аналогии с другими вьюхами).
Иначе, если она все таки реально _главная_ вьюха, то надо думать в таком направлении: 
Вьюха теоретически одна, значит и  контроллер должен знать что вьюха одна, а уже остальные вьюхи будут видны **только** в главной вьюхе.  

Если это осмысленное решение - то буду рад услышать твое объяснение и по возможности аргументы))

**Comment by p-tka4enko** [comment]
> А можешь объяснить зачем во вьюхах ты вызываешь this._model.getConfig();? Почему именно так решил получать данные из модели?

Возможно, ответ здесь #8.

> Почему тогда, если это главная(исходя из названия) вьюха, она у тебя по факту сама по себе? Она ведь отвечает лишь за ориентацию слайдера. Тогда лучше ее назвать SliderView(по аналогии с другими вьюхами).
Иначе, если она все таки реально главная вьюха, то надо думать в таком направлении:
Вьюха теоретически одна, значит и контроллер должен знать что вьюха одна, а уже остальные вьюхи будут видны только в главной вьюхе.
Если это осмысленное решение - то буду рад услышать твое объяснение и по возможности аргументы))

Думаю, проще тогда ее просто переименовать в SliderView)

**Comment by Frolikow** [comment]
> Возможно, ответ здесь #8.

Там ответа увы нету)
Поясню вопрос) мне интересен именно смысл этого вызова, какая в нем необходимость? 
У тебя идет нотифай из модели чтобы обновились вьюхи, вьюхи ловят нотифай и просят у модели данные. И собственно что меня больше всего интересует, нельзя ли сразу в нотифай класть обновленные конфиги?

> Думаю, проще тогда ее просто переименовать в SliderView)

Тут нужно подумать не только о том как легче, но и о том как правильнее) Ты сам как считаешь, какая реализация будет более правильной?

**Comment by p-tka4enko** [comment]
> Там ответа увы нету)
Поясню вопрос) мне интересен именно смысл этого вызова, какая в нем необходимость?
У тебя идет нотифай из модели чтобы обновились вьюхи, вьюхи ловят нотифай и просят у модели данные. И собственно что меня больше всего интересует, нельзя ли сразу в нотифай класть обновленные конфиги?

А что если я сделаю так: из вьюхи модель вообще уберу, а подпишет ее на модель контроллер? Тогда будет минус одна зависимость.

**Comment by Frolikow** [comment]
С одной стороны хорошо сделать вьюху пассивной) с другой стороны в origin MVC(в рамках которой проверям) вьюха хоть немного но связана с моделью.
И тут надо взвесить, или отступить от классического исполнению в пользу меньшей связанности, или оставить связь между вью и моделью, но уменьшить ее насколько это возможно

**Comment by p-tka4enko** [comment]
Думаю, малая связность не будет мешать.
