### ISSUE TITLE
Именование переменных и деструктуризация

### ISSUE THREAD

**Issue by Frolikow** [p-tka4enko/range-slider#2]
Постарайся давать такие имена, чтобы не нужно было лезть в код, или пытаться делать какие-то предположения, чтобы узнать, что за $obj1, $obj2 / projectionX(Y)1, projectionX(Y)2 и чем они отличаются. С правильным именем все это должно стать очевидно.
![image](https://user-images.githubusercontent.com/25764783/56365548-4bfcab80-621b-11e9-815a-47a0e7452942.png)
Ну и в принципе именование переменных,  с применением перечисления - плохая практика.

**Comment by Frolikow** [comment]
Тут как в предыдущих проектах, буква "c" - не очевидно, и не сразу понятно. Полное имя лучше будет. 
![image](https://user-images.githubusercontent.com/25764783/56366279-faedb700-621c-11e9-9c4d-60a282809c46.png)

И можешь сразу деструктуризацию делать

**Comment by pasha-zolotukhin** [comment]
> что за $obj1, $obj2

А если это любой объект?

**Comment by pasha-zolotukhin** [comment]
> что за $obj1, $obj2

Там любой jquery объект по сути)

**Comment by Frolikow** [comment]
> > что за $obj1, $obj2
> 
> Там любой jquery объект по сути)

Но, при этом у тебя данный метод используется 1 раз, и из названий аргументов, я бы не сказал что прям любой объект `jquery`
![image](https://user-images.githubusercontent.com/25764783/56451447-e95bfa80-6355-11e9-9146-8be48c2bc09f.png)

**Comment by pasha-zolotukhin** [comment]
Может тогда метод назвать `hintsHaveCollision` и не передавать туда аргументы, а брать их из объекта?

**Comment by Frolikow** [comment]
Да, думаю так будет лучше, только именование мне не нравиться, я бы назвал checkCollisionOfHints. На мой взгляд, пусть немного, но более ясно становиться из названия метода - что он делает

**Comment by pasha-zolotukhin** [comment]
Для projectionX(Y)1(2) пойдут названия leftHintProjectionX(Y) и rightHintProjectionX(Y)?

**Comment by Frolikow** [comment]
А ты как считаешь?) Если имя отражает смысл переменной - то подойдет) 
projectionX(Y)1(2) - смысл не отражали. Глядя на такое имя не понятно что это такое.
 
p.s. Если сомневаешься в каком-то имени, то попробуй на него посмотреть вне контекста. Например имя метода isCollision что может сказать? Столкновение? Кого, чего?) понимаешь о чем я ?

**Comment by Frolikow** [comment]
![image](https://user-images.githubusercontent.com/25764783/58621927-a39b3600-82f4-11e9-9617-bb9970401b57.png)
вот эти два метода что делают? выравнивают объект(не понятно какой) между горизонтальными/вертикальными точками? ты ведь в них передаешь только `$leftHint `или` $rightHint`.
Лучше назвать осмысленнее, и вместо `$obj` использовать `$hint `

**Comment by p-tka4enko** [comment]
Сделано.

**Comment by Frolikow** [comment]
Можешь объяснить вот этот момент?
https://github.com/p-tka4enko/range-slider/blob/d94cc7e48e53fba3ab15e1fb2c0aa3b786ba069b/src/js/View/HintView.js#L97-L99
Что именно значит имя переменной, почему решил так назвать? Мб есть какая-то практика по такому именованию?)

**Comment by p-tka4enko** [comment]
[Стайлгайд от Airbnb.](https://github.com/airbnb/javascript#comparison--nested-ternaries)

**Comment by p-tka4enko** [comment]
Последний коммит не в тему. Случайно на это ишью сослался(
